package io.openems.edge.deye.sun.hybrid.vectis;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition(//
		name = "Deye Sun hybrid Grid Meter", //
		description = "Implements the hy-switch Grid Meter for Deye Sun hybrid")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "meter0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Use external sensors", description = "Only activate this if Vectis uses external sensors")
	boolean external() default false;

	@AttributeDefinition(name = "Core-ID", description = "ID of Core component")
	String core_id() default "deyeCore0";

	@AttributeDefinition(name = "Core target filter", description = "This is auto-generated by 'Core-ID'")
	String core_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "Deye Sun hybrid Grid Meter [{id}]";
}
