package io.openems.edge.deye.sun.hybrid.pv;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition(//
		name = "Deye Sun Hybrid DC Charger PV2", //
		description = "Implements the Deye Sun Hybrid DC Charger.")
@interface ConfigPv2 {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "charger0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "PV2";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Deye Sun Hybrid Inverter-ID", description = "ID of Deye Sun Hybrid Inverter device.")
	String ess_id() default "ess0";

	@AttributeDefinition(name = "Deye Sun Hybrid Inverter target filter", description = "This is auto-generated by 'Deye Sun Hybrid Inverter-ID'.")
	String Ess_target() default "(enabled=true)";

	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID' from Deye Sun Hybrid Inverter.")
	String Modbus_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "Deye Sun Hybrid Inverter Charger PV2 [{id}]";
}