package io.openems.edge.deye.sun.hybrid.ess.charger;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition(//
		name = "Deye Sun Hybrid DC Charger", //
		description = "Implements the DC Charger for Deye Sun Hybrid Inverters.")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "charger0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Core-ID", description = "ID of Core component")
	String core_id() default "deyeCore0";

	@AttributeDefinition(name = "Core target filter", description = "This is auto-generated by 'Core-ID'")
	String core_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "Deye sun hybrid DC Charger [{id}]";
}
