= Deye Sun Hybrid Inverters

== Implemented Components:

* *Deye.SunHybrid.Core*
** This component is always required to establish the communication to the hardware device.

* *Deye.SunHybrid.Ess*
** This implements the Energy Storage System part (i.e. `ManagedSymmetricEss`) for read-only (fast internal control) or read-write (slow external control)

* *Deye.SunHybrid.Charger*
** This implements the DC Charger/MPP tracker for the photovoltaics system (i.e. `EssDcCharger`). Note that there is only one instance for both MPP trackers, because the inverter does not provide separated power values.

* *Deye.SunHybrid.PvInverter*
** This implements the inverter as a pure photovoltaics inverter (i.e. `ManagedSymmetricPvInverter`). Use this instead of Ess+Charger, if you are using the inverter purely as PV inverter without a battery.

* *Deye.SunHybrid.GridMeter*
** This implements the grid meter connected to the inverter (i.e. `ElectricityMeter`) 

== License/Dependencies

NOTE: *The configuration of the Deye.SunHybrid.Core Component requires an `identkey`. This relates to the "Partner ID" that has to be acquired from Katek Memmingen GmbH. Without the `identkey` it is not possible to establish a communication with the hardware device.**

This bundle is provided under the EPL (Eclipse Public License), but it depends on the Katek EDCOM library under `io.openems.edge.katek.edcom`, which is licensed as LGPL (GNU Lesser General Public License) by Katek Memmingen GmbH.

== Product page:
https://www.deyeinverter.com/product/hybrid-inverter-1/sun5-6ksg01lp1us-sun7-6-8ksg01lp1us-eu.html

https://github.com/OpenEMS/openems/tree/develop/io.openems.edge.deye.sun.hybrid[Source Code icon:github[]]